### ISSUE TITLE
Responsive design hides fork/edit/collect/share below 768 px

### ISSUE THREAD

**Issue by Madjosz** [codewars/codewars.com#2908]
**Describe the bug**
When the window width is 767 px or lower (e.g. in portrait mode on mobile) on a `/kata` page the right block containing the links to Fork/Edit/Collect and social media share option become invisible. That makes it impossible to access the fork option.

```css
@media (min-width: 768px)
.md\:block {
    display: block!important;
}
.hidden {
    display: none!important;
}
```

**To Reproduce**
Narrow the width of the browser window to 768 px or less.

**Expected behavior**
The buttons should just be accessible below the Details/Solutions/Forks/Discourse/Translations buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/28844868/213125678-6e92a02b-8785-494d-bf35-5f25697e0312.png)

**Browser**
Opera 94.0.4606.38
Firefox 108.0.2 (64-Bit)
