### ISSUE TITLE
Box for choosing discussion label resizes upon hovering on any items

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#988]
I don't know how to describe this, so have two pics:

Before hovering on any items:
![image](https://cloud.githubusercontent.com/assets/14909989/26660386/5f4c4d78-46aa-11e7-8aca-97d17cd736fa.png)

After hovering on an item:
![image](https://cloud.githubusercontent.com/assets/14909989/26660388/6c1edcfa-46aa-11e7-9b41-b531876db554.png)

**Comment by kazk** [comment]
This is caused by `.flyout` displayed on `hover`.

![image](https://user-images.githubusercontent.com/639336/26947184-a4ce9d82-4c46-11e7-94a6-2c53ae6df05c.png)
![image](https://user-images.githubusercontent.com/639336/26947226-cd4e1382-4c46-11e7-98aa-5b5422862e20.png)
![image](https://user-images.githubusercontent.com/639336/26946558-96549272-4c44-11e7-86bf-6c2fa58023d2.png)
![image](https://user-images.githubusercontent.com/639336/26946576-a5cdb936-4c44-11e7-98b8-071547e9a6b6.png)

```css
.dropdown dl dd .flyout {
  position: absolute;
  z-index: 12;
  color: #c9c9c9;
  background: #131414;
  padding: 15px;
  display: none;
  width: 100%;
  min-width: 240px;
  left: 100%;
  top: 0
}
```

```css
@media only screen and (min-width: 768px) {
  .dropdown dl dd:not(.is-disabled):hover .flyout {
    display:block
  }
}
```

---

I think having an overall description like @Voileexperiments suggested in #942 is more clear. I'd suggest removing these and adding #942.

If this is going to be kept, some updates/rewording is necessary.
For example, the description for "Question"

> If you are stuck trying to solve the kata, you can mark a thread as a question to get help.
> **Users who have already completed the kata will be notified and come to the rescue.**

is not true.
